jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Preload upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: ./nonexistent
          if-no-files-found: ignore

      - name: Deploy
        uses: actions/deploy-pages@v2
