name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      # Optional workaround if issue persists (shouldn't be needed with ubuntu-22.04)
      - name: Preload upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: ./nonexistent
          if-no-files-found: ignore

      - name: Deploy
        uses: actions/deploy-pages@v2
